on: pull_request

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Download vswhere
        run: |
          curl -L https://github.com/microsoft/vswhere/releases/download/2.7.1/vswhere.exe --output vswhere.exe
      - name: Download nuget
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe
      - name: Restore packages
        run: |
          nuget restore .
      - name: Build
        run: |
          setlocal enabledelayedexpansion
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
            "%%i" %*
            exit /b !errorlevel!
          )
      - name: Create archive
        run: |
          7z a -tzip AModel.zip ./AModelImport/bin/AModelImport.rhp ./AModelImport/bin/Newtonsoft.Json.dll
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./AModel.zip
          asset_name: AModel.zip
          asset_content_type: application/zip
